title: AIM Robotics
email: AIMRobotics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  FRC Team 1123 (AIM Robotics)
baseurl: ""
url: "https://frc-1123.github.io"
#twitter_username: jekyllrb
github_username:  frc-1123

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
